#!/bin/bash

source ttk.inc.sh

if [ $# -lt 1 ]; then
	echo "Usage: $(basename $0) <lang(s)>"
	exit 1
fi

if [ ! -d $SOURCE_DIR/.svn ]; then
	svn co $svnverbosity $MOZREPONAME/projects/mozilla.com/trunk/locales/en-GB $SOURCE_DIR
else
	svn up $svnverbosity $SOURCE_DIR
fi

if [ ! -d $TARGET_DIR/.svn ]; then
	svn co $svnverbosity --depth=files $MOZREPONAME/projects/mozilla.com/trunk/locales/ $TARGET_DIR
else
	svn up $svnverbosity --depth=files $TARGET_DIR
fi

for lang in $LANGS
do
	lang=get_language_pootle $lang
	if [ $lang == "templates" ]; then
		rm -rf $POT_DIR
		mkdir -p $POT_DIR/emails
		moz2po --errorlevel=$errorlevel --progress=$progress $SOURCE_DIR $POT_DIR
		txt2po --errorlevel=$errorlevel --progress=$progress $SOURCE_DIR/emails $POT_DIR/emails
		podebug --errorlevel=$errorlevel --progress=$progress --rewrite=blank $POT_DIR $POT_DIR
		rename 's/\.po$/.pot/' $(find $POT_DIR -name "*.po")
	else
		mozlang=get_language_upstream $lang
		rm -f $(find $PO_DIR/$lang -name "*.po")
		pot2po --errorlevel=$errorlevel --progress=$progress -t $PO_DIR/$lang $POT_DIR $PO_DIR/$lang

		revert_unchanged_po_git $PO_DIR $lang

		svn revert $svnverbosity -R $TARGET_DIR/$mozlang
		svn up $svnverbosity $TARGET_DIR/$mozlang
		rm -f $(find $TARGET_DIR/$mozlang -name "*.lang")
		po2moz --errorlevel=$errorlevel --progress=$progress -t $SOURCE_DIR $POUPDATED_DIR/$lang $TARGET_DIR/$mozlang
		po2txt --errorlevel=$errorlevel --progress=$progress -t $SOURCE_DIR/emails $POUPDATED_DIR/$lang/emails $TARGET_DIR/$mozlang/emails
	fi
done
